import tkinter
from tkinter import ttk
win=tkinter.Tk()
win.title('Menu Bar-Manisha')
def func():
    print('this is menu bar')
# menubar=tkinter.Menu(win)
# menubar.add_command(label='file',command=func)
# menubar.add_command(label='Edit',command=func)

# menubar.add_command(label='delete',command=func)
# menubar.add_command(label='open',command=func)
main_menu=tkinter.Menu(win)
file_menu=tkinter.Menu(main_menu,tearoff=0)
file_menu.add_command(label='New File',command=func)
file_menu.add_command(label='Open File',command=func)
file_menu.add_separator()
file_menu.add_command(label='Save',command=func)
file_menu.add_command(label='Save AS',command=func)
file_menu.add_command(label='Project',command=func)
# editfile
edit_menu=tkinter.Menu(main_menu,tearoff=0)
edit_menu.add_command(label='cut',command=func)
edit_menu.add_command(label='copy',command=func)
edit_menu.add_command(label='copy path',command=func)
edit_menu.add_command(label='copy reference',command=func)
edit_menu.add_separator()
edit_menu.add_command(label='paste',command=func)
edit_menu.add_command(label='paste from History',command=func)
edit_menu.add_command(label=' paste without Formatting',command=func)

# viewmenu

veiw_menu=tkinter.Menu(main_menu,tearoff=0)
veiw_menu.add_command(label='Tool Windows ',command=func)
veiw_menu.add_command(label='appearance',command=func)
veiw_menu.add_separator()
veiw_menu.add_command(label='Quick Documentation',command=func)
veiw_menu.add_command(label='parameter Info',command=func)
veiw_menu.add_command(label='Type info',command=func)

# codemenu
code_menu=tkinter.Menu(main_menu,tearoff=0)
code_menu.add_command(label='Generate',command=func)
code_menu.add_command(label='Surround With',command=func)
code_menu.add_command(label='Unwrap/Remove',command=func)
code_menu.add_separator()
code_menu.add_command(label='completion',command=func)
code_menu.add_command(label='folding',command=func)
# runmenu
run_menu=tkinter.Menu(main_menu,tearoff=0)
run_menu.add_command(label='Run menubar',command=func)
run_menu.add_command(label='Debuge menubar',command=func)
run_menu.add_separator()
run_menu.add_command(label='Run...',command=func)
run_menu.add_command(label='Attach to process',command=func)
run_menu.add_command(label='Edit Configuration',command=func)
# tools
tools_menu=tkinter.Menu(main_menu,tearoff=0)
tools_menu.add_command(label='Task & contexts',command=func)
tools_menu.add_separator()
tools_menu.add_command(label='Save file as template',command=func)
tools_menu.add_command(label='analyze stack Trace',command=func)
tools_menu.add_separator()
tools_menu.add_command(label='python Console',command=func)
tools_menu.add_command(label='create setup.py',command=func)
# help
help_menu=tkinter.Menu(main_menu,tearoff=0)
help_menu.add_command(label='Find action',command=func)
help_menu.add_command(label='Help',command=func)
help_menu.add_separator()
help_menu.add_command(label='Getting started',command=func)
help_menu.add_command(label='keymap Reference',command=func)
help_menu.add_command(label='Demos and Screenshots',command=func)
# windows
window_menu=tkinter.Menu(main_menu,tearoff=0)
window_menu.add_command(label='store current Layout as Default',command=func)
window_menu.add_command(label='Restore Default Layout',command=func)
window_menu.add_separator()
window_menu.add_command(label='Active Tool Window',command=func)
window_menu.add_command(label='Editors Tabs',command=func)
window_menu.add_command(label='Notification',command=func)

#cascadecode file

main_menu.add_cascade(menu=file_menu,label='File')
main_menu.add_cascade(menu=edit_menu,label='Edit')
main_menu.add_cascade(menu=veiw_menu,label='Veiw')
main_menu.add_cascade(menu=code_menu,label='Code')
main_menu.add_cascade(menu=run_menu,label='Run')
main_menu.add_cascade(menu=help_menu,label='Help')
main_menu.add_cascade(menu=window_menu,label='Window')
win.configure(menu=main_menu)
win.mainloop()