import os,shutil
# print(os.getcwd())
# os.mkdir('movies')
# os.mkdir(r'D:/movies2')
# open('manish.txt','a').close()
# print(os.listdir())
# print(os.listdir())
# for item in os.listdir(r'D:/'):
#     path=os.path.join(r'D:/',item)
#     print(path)
# os.mkdir('new')
# shutil.copytree('new','movies/new2')
# shutil.rmtree('movies/new2')
# shutil.move('new','movies/new')
# shutil.copy('abc.py','movies/abc.py')